version: 2

workflows:
  version: 2
  default:
    jobs:
      - primary
  publish-to-play-store:
    jobs:
      - publish-to-play-store

jobs:
  primary:
    docker:
      - image: mbgl/7d2403f42e:android-ndk-r16b
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Log in to Google Cloud Platform
          shell: /bin/bash -euo pipefail
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
            gcloud auth activate-service-account --key-file secret.json --project mapbox-android-demo
            rm secret.json
      - run:
          name: Export secrets for developer-config.xml
          command: |
            #!/bin/bash
            echo "${MAPBOX_DEVELOPER_CONFIG}" > SharedCode/src/main/res/values/developer-config.xml
      - run:
          name: Check code style
          command: make checkstyle
      - run:
          name: Run Firebase instrumentation tests
          command: |
            #!/bin/bash
            echo "Build seperate test apk:"
            ./gradlew :MapboxAndroidDemo:assembleGpservicesDebug --continue
            gcloud firebase test android run --type robo --app MapboxAndroidDemo/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk --device-ids shamu --os-version-ids 22 --locales en --orientations portrait --timeout 5m
      - store_artifacts:
          path: MapboxAndroidDemo/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk
  publish-to-play-store:
    docker:
      - image: mbgl/7d2403f42e:android-ndk-r16b
    working_directory: ~/code
    steps:
      requires:
        - primary
      filters:
        branches:
          only: master
      commands:
        -./gradlew publishApkRelease 
          -Dorg.gradle.project.track=alpha