version: 2

workflows:
  version: 2
  default:
    jobs:
      - primary:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
# ------------------------------------------------------------------------------
jobs:
  primary:
    docker:
      - image: mbgl/feb0443038:android-ndk-r17
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Clean gradle
          command: ./gradlew clean
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Log in to Google Cloud Platform
          shell: /bin/bash -euo pipefail
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
            gcloud auth activate-service-account --key-file secret.json --project mapbox-android-demo
            rm secret.json
      - run:
          name: Check code style
          command: make checkstyle
      - run:
          name: Generate Espresso sanity tests
          command: make sanity-test-example-activities
      - run:
          name: Run Firebase instrumentation tests
          command: |
            #!/bin/bash
            gcloud firebase test android run --type instrumentation \
            ./gradlew :MapboxAndroidDemo:assembleGpservicesDebug --continue
            ./gradlew :MapboxAndroidDemo:assembleAndroidTest --continue
            --app MapboxAndroidDemo/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk
            --test MapboxAndroidDemo/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-androidTest.apk
            --device-ids shamu --os-version-ids 22 --locales en --orientations portrait --timeout 5m
      - store_artifacts:
          path: MapboxAndroidDemo/build/outputs/apk/gpservices/debug/MapboxAndroidDemo-gpservices-debug.apk
# ------------------------------------------------------------------------------
  release:
    docker:
      - image: mbgl/feb0443038:android-ndk-r17
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "MapboxAndroidDemo/build.gradle" }}
      - run:
          name: Export developer-config.xml & Google Play authentication json
          command: |
            #!/bin/bash
            echo "${PLAY_PUBLISH_AUTH_JSON}" > android-gl-native-6d21dd280e7b.json
      - run:
          name: Release to Google Play
          command: ./gradlew publishGpservicesRelease
# ------------------------------------------------------------------------------
